Traceback (most recent call last):
  File "src/MemSum/src/MemSum_Full/train.py", line 2, in <module>
    from model import *
  File "/home/anto/SAESum-Simultaneous_Abstractive_and_Extractive_Summarization/src/MemSum/src/MemSum_Full/model.py", line 13, in <module>
    model_s = AutoModelForSeq2SeqLM.from_pretrained(model_name)
  File "/home/anto/.local/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 423, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/anto/.local/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 725, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/home/anto/.local/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 432, in __getitem__
    raise KeyError(key)
KeyError: 'pegasus_x'
Requirement already satisfied: transformers in /home/anto/.local/lib/python3.8/site-packages (4.20.1)
Requirement already satisfied: filelock in /home/anto/.local/lib/python3.8/site-packages (from transformers) (3.7.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.1.0 in /home/anto/.local/lib/python3.8/site-packages (from transformers) (0.8.1)
Requirement already satisfied: numpy>=1.17 in /home/anto/.local/lib/python3.8/site-packages (from transformers) (1.23.0)
Requirement already satisfied: packaging>=20.0 in /home/anto/.local/lib/python3.8/site-packages (from transformers) (23.1)
Requirement already satisfied: pyyaml>=5.1 in /home/anto/.local/lib/python3.8/site-packages (from transformers) (6.0)
Requirement already satisfied: regex!=2019.12.17 in /home/anto/.local/lib/python3.8/site-packages (from transformers) (2022.6.2)
Requirement already satisfied: requests in /home/anto/.local/lib/python3.8/site-packages (from transformers) (2.31.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.13,>=0.11.1 in /home/anto/.local/lib/python3.8/site-packages (from transformers) (0.12.1)
Requirement already satisfied: tqdm>=4.27 in /home/anto/.local/lib/python3.8/site-packages (from transformers) (4.64.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/anto/.local/lib/python3.8/site-packages (from huggingface-hub<1.0,>=0.1.0->transformers) (4.3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/anto/.local/lib/python3.8/site-packages (from requests->transformers) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/anto/anaconda3/envs/wandb-env/lib/python3.8/site-packages (from requests->transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/anto/.local/lib/python3.8/site-packages (from requests->transformers) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/anto/anaconda3/envs/wandb-env/lib/python3.8/site-packages (from requests->transformers) (2023.5.7)
Note: you may need to restart the kernel to use updated packages.
UsageError: Line magic function `%sudo` not found.
[sudo] password for anto:
